# Gemfile

source 'https://rubygems.org'
ruby "2.3.7"

gem "sinatra"
gem "rake"
gem "activerecord"
gem "sinatra-activerecord"
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'bcrypt'
gem 'aws-sdk'
gem 'fileutils'

group :development do
  gem 'sqlite3'
  gem "tux"
end

group :production do
  gem 'pg'
end